import './globals.css';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

const roboto = localFont({
  src: [
    {
      path: './fonts/roboto/Roboto-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/roboto/Roboto-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/roboto/Roboto-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} font-body`}>{children}</body>
    </html>
  );
}
